import "./globals.css";
import Providers from "./providers";
import Header from "../components/header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark bg-background-gradient">
      <body>
        <div className="container mx-0 px-0 min-w-full">
          <Providers>
            <Header />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
